### ISSUE TITLE
django.contrib.gis

### ISSUE THREAD

**Issue by MAM-SYS** [jobguywork/backend#37]
hello
first of all thanks for this wonderful project
i started to read the codes of project and i found out that this project is using gis app but it is not added in the INSTALLED_APP
am i right?
so i decided to start my first contribution with this little issue
and spend more time to help, if i can
خیلی مخلصیم

**Comment by sbabashahi** [comment]
Hello, there is a problem. At first there was an idea that we save company location and then we could help in routing people to that location. But as project developed, the requirements changed and I think there is no need to support gis furthermore, so maybe we need to remove it from project. please wait for a decision about gis feature, and if you have any idea using gis we would be happy to hear from you.

**Comment by sbabashahi** [comment]
@MAM-SYS as I mentioned this issue with others, we decided to continue having gis in project. So you are good to go. Sorry to keep you waiting and thanks for creating issue before contributing. :)

**Comment by MAM-SYS** [comment]
thanks
so if the decision is to keeping gis in the project and if you guys want, i can make first pull request for this issue for start
but i am working more for some Unit Tests or some code developing
