### ISSUE TITLE
Installing Geospatial libraries

### ISSUE THREAD

**Issue by MAM-SYS** [jobguywork/backend#39]
hello again
i have found something about the Dockerfile
when i try to make a container it says that the gdal library is not installed
i think we should mention on the Dockerfile to install Geospatial libraries inside the docker container like gdal-bin and others dependencies
am i right?

**Comment by amireshoon** [comment]
According to [GitHub action workflows](https://github.com/jobguywork/backend/actions) and [GitHub Packages](https://github.com/orgs/jobguywork/packages?repo_name=backend) for building Dockerfile, there is no error, However, can you add some logs or vision that we could work on it maybe?

**Comment by MAM-SYS** [comment]
so i made some changes for this issue like ([Geospatial libraries](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/geolibs/) added to the Dockerfile for gdal error) and (change postgres image to [postgis](https://registry.hub.docker.com/r/postgis/postgis/) image because of some error for installing postgis extension in postgresql)
i faced this errors when i was trying to make a container from docker-compose
am I on the right way for this issue?

**Comment by amireshoon** [comment]
Send your changes by creating a pr in develop branch with an understanding title.

About docker-compose file include your logs.
