### ISSUE TITLE
create_initial_data

### ISSUE THREAD

**Issue by MAM-SYS** [jobguywork/backend#46]
hello friends
i was trying to use [***create_initial_data***](https://github.com/jobguywork/backend/blob/e88b6e6173a00524a80f35ddcb3537f4de7bd89f/utilities/views.py#L50) function to create test data on my system
but when the process comes to the [Industry](https://github.com/jobguywork/backend/blob/e88b6e6173a00524a80f35ddcb3537f4de7bd89f/utilities/views.py#L135) or [Pros](https://github.com/jobguywork/backend/blob/e88b6e6173a00524a80f35ddcb3537f4de7bd89f/utilities/views.py#L145) or [Cons](https://github.com/jobguywork/backend/blob/e88b6e6173a00524a80f35ddcb3537f4de7bd89f/utilities/views.py#L153) we face with 400 Bad Request
i found that the problem is because of logo data that we are sending to the server
because we have a function that [check the existence of the logo](https://github.com/jobguywork/backend/blob/e88b6e6173a00524a80f35ddcb3537f4de7bd89f/utilities/utilities.py#L124) and it raise ValidationError because the file does not exist physically
so i decided just to remove logo field data from requests that we are sending to the server(logo can be null) and problem solved
i am not sure that it is the best solution for this issue but if you confirm this i can send the changes
****this is the changes photo:****
![logo changes](https://user-images.githubusercontent.com/15687474/120818596-0240bd80-c568-11eb-8cf3-80250bb12c5c.png)
thanks again

**Comment by sbabashahi** [comment]
Another way could be: 
```
from djang.conf import settings

def check_file_exist(path):
  if settings.DEBUG:
      return 
  else:
      resp = requests.post('https://upload.jobguy.work/validate/', json={'path': path})
      if resp.status_code == 404:
          raise serializers.ValidationError(_('File does not exist'))
      elif resp.status_code == 200:
          return
      else:
          raise serializers.ValidationError(_('There is an error with media server connection...'))
```

**Comment by MAM-SYS** [comment]
exactly
your idea is better
@sbabashahi
