### ISSUE TITLE
overriding save() method

### ISSUE THREAD

**Issue by MAM-SYS** [jobguywork/backend#48]
hello guys, hope you are all fine
i faced an issue about overriding some of ***save()*** method in some models like [Industry](https://github.com/jobguywork/backend/blob/ac7dfd3601f9a5e3814c56e8b44ca888cbf22385/company/models.py#L9) or [Company](https://github.com/jobguywork/backend/blob/ac7dfd3601f9a5e3814c56e8b44ca888cbf22385/company/models.py#L74)
i think save() method in these models doesn't have all necessary parameters(just have **force_update** and **force_update**)
#### so i face with this error when try to create an instance of these models:
![using error in save() override](https://user-images.githubusercontent.com/15687474/120927382-f1be4d80-c6f5-11eb-92c3-f9a0227a36d9.png)
i think we should pass all parameters save(self, force_insert=False, force_update=False, using=None, update_fields=None)
or save(self, *args, **kwargs)
am i right?
sorry if i disturb a lot

**Comment by sbabashahi** [comment]
I think beet practice is using *args, **kwargs, do you work on this issue?

**Comment by MAM-SYS** [comment]
Yes
I will send the changes
Thanks

**Comment by sbabashahi** [comment]
Closed by #49
