### ISSUE TITLE
comma separate salary numbers

### ISSUE THREAD

**Issue by lmn3x** [jobguywork/backend#74]
hi jobguy
i think if you make salary numbers comma separated , it would be easier to read.

**Comment by sbabashahi** [comment]
Hi @lmn3x 

This issues does not relate to backend, try reporting it in [website]([url](https://github.com/jobguywork/website/issues)). I think you mean adding salary in creating review or interview, am I right? Please add image or more description to clarify your issue

**Comment by lmn3x** [comment]
no no, you were right, its related to website repo..sorry

for a sec, i thought you use django template for front-end.

i'll add an issue in website with photos.
