### ISSUE TITLE
Jobguy data

### ISSUE THREAD

**Issue by amireshoon** [jobguywork/backend#79]
Due to Jobguy is down now and we (All developers) Know that jobguy tried his best to bring sight of understanding, but some people need to be in dark. I suggest that Jobguy data be public so users can add more reviews and maybe some one carry on what you started and not be stopped by people like this...

از اونجایی که جاب کای رسما اعلام کرده فعالیت نمیکنه و ما همه برنامه نویسان میدونیم که جاب گای همه تلاششو کرد تا به ما کمک کنه ولی بعضی از مردم نیاز دارن توی تاریکی قدم بزنند. من پیشنهاد میکنم(و جمعی دیگر توی توییتر) که دیتای جاب گای پابلیک بشه تا بقیه افراد نقد های خودشون رو همچنان اضافه کنند و شاید بعضی ها چیزی که شما شروع کردید رو ادامه بدید و توسط همچین آدم هایی متوقف نشه.

**Comment by ghobadkhan** [comment]
سلام. شدیدا موافقم. اگر برای پابلیک شدنش نیاز به کمکی هم هست در خدمتم.
